/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WardenRouteImport } from './routes/warden'
import { Route as StudentRouteImport } from './routes/student'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WardenRoomsRouteImport } from './routes/warden.rooms'
import { Route as WardenLeaveRouteImport } from './routes/warden.leave'
import { Route as WardenGateRouteImport } from './routes/warden.gate'
import { Route as WardenComplaintsRouteImport } from './routes/warden.complaints'
import { Route as StudentVisitorsRouteImport } from './routes/student.visitors'
import { Route as StudentLeaveRouteImport } from './routes/student.leave'
import { Route as StudentComplaintsRouteImport } from './routes/student.complaints'
import { Route as StudentBillingRouteImport } from './routes/student.billing'
import { Route as AdminOccupancyRouteImport } from './routes/admin.occupancy'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAlertsRouteImport } from './routes/admin.alerts'

const WardenRoute = WardenRouteImport.update({
  id: '/warden',
  path: '/warden',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WardenRoomsRoute = WardenRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => WardenRoute,
} as any)
const WardenLeaveRoute = WardenLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => WardenRoute,
} as any)
const WardenGateRoute = WardenGateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => WardenRoute,
} as any)
const WardenComplaintsRoute = WardenComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => WardenRoute,
} as any)
const StudentVisitorsRoute = StudentVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLeaveRoute = StudentLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => StudentRoute,
} as any)
const StudentComplaintsRoute = StudentComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => StudentRoute,
} as any)
const StudentBillingRoute = StudentBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => StudentRoute,
} as any)
const AdminOccupancyRoute = AdminOccupancyRouteImport.update({
  id: '/occupancy',
  path: '/occupancy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/guest': typeof GuestRoute
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/warden': typeof WardenRouteWithChildren
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/occupancy': typeof AdminOccupancyRoute
  '/student/billing': typeof StudentBillingRoute
  '/student/complaints': typeof StudentComplaintsRoute
  '/student/leave': typeof StudentLeaveRoute
  '/student/visitors': typeof StudentVisitorsRoute
  '/warden/complaints': typeof WardenComplaintsRoute
  '/warden/gate': typeof WardenGateRoute
  '/warden/leave': typeof WardenLeaveRoute
  '/warden/rooms': typeof WardenRoomsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/guest': typeof GuestRoute
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/warden': typeof WardenRouteWithChildren
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/occupancy': typeof AdminOccupancyRoute
  '/student/billing': typeof StudentBillingRoute
  '/student/complaints': typeof StudentComplaintsRoute
  '/student/leave': typeof StudentLeaveRoute
  '/student/visitors': typeof StudentVisitorsRoute
  '/warden/complaints': typeof WardenComplaintsRoute
  '/warden/gate': typeof WardenGateRoute
  '/warden/leave': typeof WardenLeaveRoute
  '/warden/rooms': typeof WardenRoomsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/guest': typeof GuestRoute
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/warden': typeof WardenRouteWithChildren
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/occupancy': typeof AdminOccupancyRoute
  '/student/billing': typeof StudentBillingRoute
  '/student/complaints': typeof StudentComplaintsRoute
  '/student/leave': typeof StudentLeaveRoute
  '/student/visitors': typeof StudentVisitorsRoute
  '/warden/complaints': typeof WardenComplaintsRoute
  '/warden/gate': typeof WardenGateRoute
  '/warden/leave': typeof WardenLeaveRoute
  '/warden/rooms': typeof WardenRoomsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/guest'
    | '/login'
    | '/student'
    | '/warden'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/occupancy'
    | '/student/billing'
    | '/student/complaints'
    | '/student/leave'
    | '/student/visitors'
    | '/warden/complaints'
    | '/warden/gate'
    | '/warden/leave'
    | '/warden/rooms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/guest'
    | '/login'
    | '/student'
    | '/warden'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/occupancy'
    | '/student/billing'
    | '/student/complaints'
    | '/student/leave'
    | '/student/visitors'
    | '/warden/complaints'
    | '/warden/gate'
    | '/warden/leave'
    | '/warden/rooms'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/guest'
    | '/login'
    | '/student'
    | '/warden'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/occupancy'
    | '/student/billing'
    | '/student/complaints'
    | '/student/leave'
    | '/student/visitors'
    | '/warden/complaints'
    | '/warden/gate'
    | '/warden/leave'
    | '/warden/rooms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  GuestRoute: typeof GuestRoute
  LoginRoute: typeof LoginRoute
  StudentRoute: typeof StudentRouteWithChildren
  WardenRoute: typeof WardenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warden': {
      id: '/warden'
      path: '/warden'
      fullPath: '/warden'
      preLoaderRoute: typeof WardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warden/rooms': {
      id: '/warden/rooms'
      path: '/rooms'
      fullPath: '/warden/rooms'
      preLoaderRoute: typeof WardenRoomsRouteImport
      parentRoute: typeof WardenRoute
    }
    '/warden/leave': {
      id: '/warden/leave'
      path: '/leave'
      fullPath: '/warden/leave'
      preLoaderRoute: typeof WardenLeaveRouteImport
      parentRoute: typeof WardenRoute
    }
    '/warden/gate': {
      id: '/warden/gate'
      path: '/gate'
      fullPath: '/warden/gate'
      preLoaderRoute: typeof WardenGateRouteImport
      parentRoute: typeof WardenRoute
    }
    '/warden/complaints': {
      id: '/warden/complaints'
      path: '/complaints'
      fullPath: '/warden/complaints'
      preLoaderRoute: typeof WardenComplaintsRouteImport
      parentRoute: typeof WardenRoute
    }
    '/student/visitors': {
      id: '/student/visitors'
      path: '/visitors'
      fullPath: '/student/visitors'
      preLoaderRoute: typeof StudentVisitorsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/leave': {
      id: '/student/leave'
      path: '/leave'
      fullPath: '/student/leave'
      preLoaderRoute: typeof StudentLeaveRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/complaints': {
      id: '/student/complaints'
      path: '/complaints'
      fullPath: '/student/complaints'
      preLoaderRoute: typeof StudentComplaintsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/billing': {
      id: '/student/billing'
      path: '/billing'
      fullPath: '/student/billing'
      preLoaderRoute: typeof StudentBillingRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/occupancy': {
      id: '/admin/occupancy'
      path: '/occupancy'
      fullPath: '/admin/occupancy'
      preLoaderRoute: typeof AdminOccupancyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminOccupancyRoute: typeof AdminOccupancyRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertsRoute: AdminAlertsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminOccupancyRoute: AdminOccupancyRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentBillingRoute: typeof StudentBillingRoute
  StudentComplaintsRoute: typeof StudentComplaintsRoute
  StudentLeaveRoute: typeof StudentLeaveRoute
  StudentVisitorsRoute: typeof StudentVisitorsRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentBillingRoute: StudentBillingRoute,
  StudentComplaintsRoute: StudentComplaintsRoute,
  StudentLeaveRoute: StudentLeaveRoute,
  StudentVisitorsRoute: StudentVisitorsRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface WardenRouteChildren {
  WardenComplaintsRoute: typeof WardenComplaintsRoute
  WardenGateRoute: typeof WardenGateRoute
  WardenLeaveRoute: typeof WardenLeaveRoute
  WardenRoomsRoute: typeof WardenRoomsRoute
}

const WardenRouteChildren: WardenRouteChildren = {
  WardenComplaintsRoute: WardenComplaintsRoute,
  WardenGateRoute: WardenGateRoute,
  WardenLeaveRoute: WardenLeaveRoute,
  WardenRoomsRoute: WardenRoomsRoute,
}

const WardenRouteWithChildren =
  WardenRoute._addFileChildren(WardenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  GuestRoute: GuestRoute,
  LoginRoute: LoginRoute,
  StudentRoute: StudentRouteWithChildren,
  WardenRoute: WardenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
